stages:
  - build-image

编译镜像:
  stage: build-image
  image:
    name: boker-hub-registry.cn-shanghai.cr.aliyuncs.com/poker-public/runner-build:svn
  script:
    - echo "github demo"
    - sleep 3000000000
  tags:
    - k3s-runner
